accelerator: null
accumulate_grad_batches: 2
amp_backend: native
amp_level: O2
aug_prob: 0.5
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 8
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
dataset: sentence_data
default_root_dir: null
deterministic: false
distributed_backend: null
encoder_lr: 2.0e-05
eps: 1.0e-06
fast_dev_run: false
flush_logs_every_n_steps: 100
fold_num: 0
gpus: 1
gradient_clip_algorithm: norm
gradient_clip_val: 0.0
input_method: 3
is_pretrain_model: false
kfold: 0
label_set:
- positive
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
load_best: true
load_dir: null
load_v_num: 0
load_ver: null
log_dir: rct/fixed/train_logging/train_1800_llm_human_labelled_0~0800
log_every_n_steps: 50
log_gpu_memory: null
logger: true
logger_name: lightning_classification
logger_project: hedges
logger_type: TensorBoard
loss: ce
loss_cal_type: loss_f
lr: 5.0e-05
lr_decay_min_lr: 1.0e-05
lr_decay_rate: 0.5
lr_decay_steps: 20
lr_scheduler: null
max_epochs: 100
max_steps: null
max_time: null
min_epochs: null
min_steps: null
mode: train+test
model_name: bert_classifier
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
no_augment: false
nr_frozen_epochs: 1
num_labels: 2
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_workers: 8
optimizer: adam
output_method: 1
overfit_batches: 0.0
plugins: null
precision: 32
predict_data_dir: null
prepare_data_per_node: true
pretrain_model_parameter: null
pretrained_model_name_or_path: /mnt/Data.Common/Chenh/data/transformers/dmis-lab_biobert-base-cased-v1.2
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
seed: 2333
stochastic_weight_avg: false
sync_batchnorm: false
terminate_on_nan: false
test_data_dir: /mnt/Data.Common/Chenh/PycharmProjects/InformationExtraction/dataset/classification_dataset/rct_literature/precision_tumor_classification/data/initial_200/test_200_human_labelled.csv
tpu_cores: null
track_grad_norm: -1
train_data_dir: /mnt/Data.Common/Chenh/PycharmProjects/InformationExtraction/dataset/classification_dataset/rct_literature/precision_tumor_classification/data/initial_200/train_1800_llm_human_labelled_0~0800.csv
truncated_bptt_steps: null
val_check_interval: 1.0
val_data_dir: /mnt/Data.Common/Chenh/PycharmProjects/InformationExtraction/dataset/classification_dataset/rct_literature/precision_tumor_classification/data/initial_200/val_1800_llm_human_labelled_0~0800.csv
val_list:
- acc
- f1
- eval_subtag
vec_max_len: 512
weight_decay: 1.0e-06
weights_save_path: null
weights_summary: top
